backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "angebot"
    label: "Angebot"
    folder: "src/angebote"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Body", name: "body", widget: "markdown"}